### ISSUE TITLE
Documentation website supports permanent URLs

### ISSUE THREAD

**Issue by dbuduev** [cerbos/cerbos#273] opened 2021-09-03 02:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Assuming `0.6.0` is the latest release, the page `https://docs.cerbos.dev/cerbos/0.6.0/policies/index.html` is accessible by `https://docs.cerbos.dev/cerbos/(latest|current)/policies/index.html` URL or simply by `https://docs.cerbos.dev/cerbos/policies/index.html` URL.

### What would the ideal solution look like to you?

The documentation website is bookmark friendly, so I do no run into the following issue. I bookmarked a page when the `0.5.0` version was the latest, Cerbos next version was released, the bookmarked link gives "Page Not Found" page.

### Anything else?

Antora, which is used for website generation, seems to allow this scenario `https://gitlab.com/antora/antora/-/issues/314`

**Comment by emreb** [comment] 2021-09-03 07:41
👍🏼 . Would be great to fix this as I have run into this issue multiple times already.

**Comment by charithe** [comment] 2021-09-03 08:06
I have been building the foundation for this since #229. The problem is that Antora has two outstanding issues: Git LFS support and symlink support. LFS support has already landed and symlinks work in the latest tip. There were a few other minor issues that needs to be fixed upstream. As soon as they stabilise, we can roll out versioned docs.

**Comment by charithe** [comment] 2021-09-03 13:41
I got things mixed up a bit. LFS support hasn't landed yet and that's the major blocker because images are broken on all versions except for the "prerelease" version. See https://613222970a7c8c9406fc0ec6--cerbos-docs.netlify.app/cerbos/latest/index.html.

As soon as https://gitlab.com/antora/antora/-/issues/185 is resolved, we can push things through and get the broken links working again.

**Closed** 2021-09-17 14:11 UTC
Labels: documentation, feature, triage
